### ISSUE TITLE
Syntax highlighting is broken on github

### ISSUE THREAD

**Issue by AlexDaniel** [kensanata/oddmuse#10]
Looking at [wiki.pl](https://github.com/kensanata/oddmuse/blob/master/wiki.pl), there's something wrong with it. Comments are not highlighted at all, and the rest looks weird. Does it render it with perl 6 or prolog renderer? And if so, why?

**Comment by kensanata** [comment]
Looks like a GitHub bug to me—and no obvious way to fix it.

**Comment by AlexDaniel** [comment]
It is possible that it does not like the space here:
```
#! /usr/bin/perl
```
But that's just a guess.

**Comment by kensanata** [comment]
I had the same suspicion and checked yesterday. Found an example from the earliest days of Unix saying it was ok.

**Comment by AlexDaniel** [comment]
It may be OK, but github may not understand it. So we can either remove the space or submit a bug report for the github language detection. Well, if that's the case.

**Comment by kensanata** [comment]
Feel free to give it a try?

**Comment by kensanata** [comment]
Then again, [this module](https://github.com/kensanata/oddmuse/blob/master/modules/404handler.pl) looks OK and it has the same shebang?

**Comment by kensanata** [comment]
Also, looking at the source:
```
<div itemprop="text" class="blob-wrapper data type-prolog">
```

**Comment by kensanata** [comment]
[More info](https://github.com/github/linguist/issues/3230)…

**Comment by kensanata** [comment]
I added `.gitattributes` but it seems to have no immediate effect. Perhaps we need to wait for a bit?

**Comment by AlexDaniel** [comment]
Yes, seems to be ok now!
