### ISSUE TITLE
Idea for detecting wanted pages

### ISSUE THREAD

**Issue by felixp7** [kensanata/oddmuse#11]
I've read what the OddMuse site has to say about that, and I agree that detecting wanted pages by scanning the database for links is difficult if not impossible. But it's such a useful feature, something ought to be tried. Here's my idea: when someone clicks through to a non-existent page, record it somewhere as wanted. Once created, it can be removed from the list. Won't catch everything, of course, but what it does catch will be useful, and without consuming significant resources either.

**Comment by AlexDaniel** [comment]
Here's a relevant line of code:
https://github.com/kensanata/oddmuse/blob/80a30a9102d82f9082890694057527332807f8ba/wiki.pl#L1374

Looking at it, maybe you can simply wrap around BrowsePage and store all 404 hits.

What about something like this?
```perl
*OldBrowsePage = \&BrowsePage;
*BrowsePage = \&NewBrowsePage;

sub NewBrowsePage {
    my ($id, $raw, $comment, $status) = @_;
    if ($status eq '404 NOT FOUND') {
        my $filename = "$DataDir/404.log";
        open(my $fh, '>>', $filename) or die "Could not open file '$filename' $!";
        say $fh "$id";
        close $fh;
    }
    OldBrowsePage(@_);
}
```
(totally untested)

I guess it also needs some extra code during [Maintenance](https://oddmuse.org/wiki/Maintenance) to remove duplicates and pages that were created, but maybe that's a good start.

**Comment by kensanata** [comment]
Actually, bots would be crawling the site anyway, so the wanted pages list might be better than expected?

**Comment by felixp7** [comment]
In theory. But if done in the 404 handler, it will yield a lot of false positives as people type garbage into the address bar so see what happens. Should be done at the link traversal level. Better yet, when a page with links to non-existent pages is rendered, since at that point you *have* to know if each destination page exists or not in order to render the respective links accordingly.

**Comment by AlexDaniel** [comment]
> it will yield a lot of false positives as people type garbage into the address bar so see what happens

I thought about it, and it felt like a great feature :) (e.g. you renamed a page but a lot external resources were linking to it, here's a reminder to put a redirect on your side). I may be wrong though.

**Comment by kensanata** [comment]
So, is this resolved, or is there still something we need to do?

**Comment by felixp7** [comment]
Since it was just food for thought and not exactly urgent, I guess it could be closed and kept for future reference. Thank you!
