### ISSUE TITLE
other HTTP status code than 404 for empty comment pages

### ISSUE THREAD

**Issue by greenfive** [kensanata/oddmuse#12]
I suggest changing the 404 HTTP status code for empty comment pages to something else, e.g. 200/OK, as having many internal 404 links negatively affects the pagerank for search engines, as it may look like the page is not well cared for (as the page owner is responsible for local broken links, in contrast to external links of which he has no control of). Often a wiki only has comment pages for very few of the pages, so that creates a large overhead of 404s.
Even if the comment page contains no comments, it has content and is not non-existent (= 404): headers, footers, and even a "Create this page" link to add further content to that page. And yes, I do understand the logic behind why it was chosen to return a 404.

**See also: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html**
_"The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent. The 410 (Gone) status code SHOULD be used if the server knows, through some internally configurable mechanism, that an old resource is permanently unavailable and has no forwarding address. This status code is commonly used when the server does not wish to reveal exactly why the request has been refused, or when no other response is applicable."_

In our case however the server in fact has found something matching the Request-URI and the request hasn't been refused.

**Comment by kensanata** [comment]
Hm, I feel uncomfortable about this. But perhaps you are right?

**Comment by AlexDaniel** [comment]
I'm pretty sure that this is right. The 404 comes from the implementation detail that comment pages are just pages, but 404 is not the right answer. The comment page is just empty, but it does *exist* (and it was *found* in a way) if the original page exists.

**Comment by kensanata** [comment]
I like this qualification: “does exist if the original page exists.”

**Comment by AlexDaniel** [comment]
I think it just needs another condition around here:
https://github.com/kensanata/oddmuse/blob/e4d159307b87c637a611c3b9540823c37bf6411e/wiki.pl#L1373-L1374

Something like:
```perl
} elsif ($id ~~ /$CommentsPattern/ and $1 and $IndexHash{$1}) {
  # original page exists, so don't give 404
  BrowsePage($id, GetParam('raw', 0)) if ValidIdOrDie($id);
} else { # new page! 
…
```
And that's it?

**Comment by kensanata** [comment]
I wonder whether c85e8b8 solves this. It does not use smart matching (the perlop manpage tells me that 5.10.1 is different from 5.10) and it doesn't test for "successful match but empty $1". What do you think?

**Comment by AlexDaniel** [comment]
@kensanata ah, ``~~`` is a perl6-ism, sorry.

I think you should test for ``$1``. It may be undefined in some cases ([depending on the pattern](https://oddmuse.org/wiki/Comment_Pages#CommentsPattern)), and you'd get a “Use of uninitialized value $1 in hash element” warning. Also, ``ValidIdOrDie`` check is probably needed.

**Comment by kensanata** [comment]
I think `m//` in scalar context returns true on a match and false without a match. You're thinking of the case where the comment page pattern doesn't have a grouping expression in the first place? Hm, you are right. (248af82)
We definitely don't want to die if the comment page is valid but the main page is invalid, right? In that case, we might simply want the default 404 response. And hopefully only valid pages get created in the first place, so there are only valid pages in `%IndexHash` and thus we should be fine?

**Comment by AlexDaniel** [comment]
Ah, right. Yeah.

@greenfive can you test it?

**Comment by greenfive** [comment]
@AlexDaniel Tested:

1. Empty comment page for existing page: 200
2. Empty comment page for non-existing page: 404
3. Comment page for existing page: 200

Seems resolved, issue can be closed. Thanks alot for your efforts!

**Comment by AlexDaniel** [comment]
Thanks!

Well, there's one more case – non-empty comment page for non-existing page. That should give 200 :)
