### ISSUE TITLE
Diffing a revision range only shows the last commit message

### ISSUE THREAD

**Issue by m4z** [kensanata/oddmuse#18]
Greetings, my company uses OddMuse for 13+ years, I use it for 10+ years, and we are very happy with it, thanks!

I never noticed this until today: When diffing a page over multiple changes, like in the following example, only the last "commit message" (or whatever the term in OddMuse lingo is), if non-empty, is shown, which can be quite misleading, because the message doesn't summarize what's in the full diff: [emacswiki.org SiteMap range diff](https://www.emacswiki.org/emacs?action=browse&diff=1&id=SiteMap&revision=&diffrevision=1374&Compare=Compare) (example taken from emacswiki.org because I couldn't quickly find a page with more than 2 revisions on oddmuse.org)

Is this intentional? I couldn't find any info on this (my only source of info being the [Browse Action page](https://oddmuse.org/wiki/Browse_Action)); I expected to see the messages of all the revisions in the diff range.

This applies to
* OddMuse `2.3.7` (the version we are still using),
* `2.3.13-33-g91e054ce` (the version of emacswiki.org) and
* possibly newer versions (I haven't checked).

**Comment by AlexDaniel** [comment]
Nice catch!

**Comment by kensanata** [comment]
I think we never showed anything but the latest version because that's simply the easiest solution. Everything else would have required scanning the rc.log file, or opening all the keep files affected. Then again, why not... I'll see what I can do.

**Comment by kensanata** [comment]
Something like c2231b9e?

**Comment by kensanata** [comment]
I might switch the HTML around in case we have multiple changes. Using a bullet list, for example.

**Comment by kensanata** [comment]
I think I'm done, now. What do you think?

**Comment by kensanata** [comment]
Luckily somebody had pushed me to add XSS tests to Oddmuse, so don't forget that last commit. 🙄

**Comment by m4z** [comment]
Thanks for the super-quick response! I'm a perl noob, so I had to fire up a test wiki; I'm perfectly happy with what you came up with just like that, thank you very much! (I also like the deduplication of identical messages, good catch!)
