### ISSUE TITLE
HTTPS on OddMuse

### ISSUE THREAD

**Issue by KeiroD** [kensanata/oddmuse#3]
Hi, I'm sure you already noticed, but... fyi: Your oddmuse.org domain now has an invalid Let's Encrypt SSL certificate. You might... wanna renew that. :P

**Comment by kensanata** [comment]
What's weird is that I got an email today about four other domains expiring in 19 days. How strange. I renewed all the domains and it seems that the problem is fixed, so there's that.

**Comment by KeiroD** [comment]
Glad to hear you got it resolved... and that is strange. Wonder why you didn't get the e-mail for oddmuse.org? Only thing I can think of is that that `letsencrypt-auto` or `letsencrypt` didn't have an e-mail in a `cli.ini` or something similar for e-mail notifications.

Edit: Can confirm site's good to go regarding SSL. :+1:

**Comment by kensanata** [comment]
Even stranger. I'm suspecting a bug. Half an hour after you posted this:

Your certificate (or certificates) for the names listed below will expire in 19 days (on 01 Apr 16 09:08 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

...
oddmuse.org
...

**Comment by KeiroD** [comment]
O_o

... I must be a harbinger of d00m! >_> Sorry?

**Comment by kensanata** [comment]
Haha, no worries. :+1:
