### ISSUE TITLE
README incomplete (for openSUSE at least)

### ISSUE THREAD

**Issue by m4z** [kensanata/oddmuse#5]
README.creole seems to be missing the following:
`sudo chown www-data.www-data /usr/lib/cgi-bin/wiki.pl`[0]

It should be placed right after:

```
sudo wget -O /usr/lib/cgi-bin/wiki.pl \
  http://git.savannah.gnu.org/cgit/oddmuse.git/plain/wiki.pl
sudo chmod +x /usr/lib/cgi-bin/wiki.pl
```

Otherwise, when running on openSUSE Leap 42.1, apache logs the following (different path here) when trying to visit the site:

```
==> /var/log/apache2/oddmuse-test_80-error.log <==
[Tue Aug 16 16:00:46.543472 2016] [cgi:error] [pid 18917] [client […]] AH01215: (13)Permission denied: exec of '/srv/oddmuse/cgi-bin/wiki.pl' failed: /srv/oddmuse/cgi-bin/wiki.pl
[Tue Aug 16 16:00:46.543968 2016] [cgi:error] [pid 18917] [client […]] End of script output before headers: wiki.pl
```

I would expect this to be an issue on other distros, too.

[0]:  The openSUSE equivalent is `sudo chown wwwrun.root /usr/lib/cgi-bin/wiki.pl`

**Comment by m4z** [comment]
Also, probably `s/used in out instructions/used in our instructions/`

**Comment by kensanata** [comment]
Thanks! I think that closes it?

**Comment by m4z** [comment]
Yes, thank you very much. (The openSUSE part was meant to be JFYI because I think it clutters the docs a bit and is pretty straightforward, but it's of course your choice to include it.)
