### ISSUE TITLE
Link accessibility issue

### ISSUE THREAD

**Issue by felixp7** [kensanata/oddmuse#8]
Hi there! When rendering links to non-existent pages, OddMuse only makes the question mark clickable. That's quite a small target to hit with a mouse, which makes editing uncomfortable. I believe the page name should also be included in the link. Thank you!

**Comment by AlexDaniel** [comment]
Yeah.

Alternatively, you can try [``$UseQuestionmark = 0``](https://oddmuse.org/wiki/Link_Pattern#UseQuestionmark).

**Comment by felixp7** [comment]
Right, but then I need special CSS just to tell links apart, and as you point out on the website, that raises a different kind of accessibility issue. Oh well.

**Comment by kensanata** [comment]
I wonder what this does, if $UseQuestionmark is good enough?
https://oddmuse.org/wiki/No_Questionmarks_Extension

**Comment by felixp7** [comment]
Likely a leftover since before that feature was in core. I get a feeling that many features have moved in and out over time. The comment form used to be an extension years ago, for instance.

**Comment by AlexDaniel** [comment]
… I didn't know about that :)

**Comment by kensanata** [comment]
I guess it could serve as a model for the kind of feature Felix wants?

**Comment by felixp7** [comment]
What I want is the link to stay ugly and very noticeable, but be easier to click. Though on the other hand someone looking at the site asked me if those links were broken...

Clearly it's not easy to figure out how best to format a link so that it suggests "come put something in this empty corner", while being accessible. But it seems important to me.

**Comment by kensanata** [comment]
I still wonder what to do… This would be an untested replacement for Felix's config file:

```perl
sub GetPageOrEditLink { # use GetPageLink and GetEditLink if you know the result!
  my ($id, $text, $bracket, $free) = @_;
  $id = FreeToNormal($id);
  my ($class, $resolved, $title, $exists) = ResolveId($id);
  if (not $text and $resolved and $bracket) {
    $text = BracketLink(++$FootnoteNumber);
    $class .= ' number';
    $title = NormalToFree($id);
  }
  my $link = $text || NormalToFree($id);
  if ($resolved) { # anchors don't exist as pages, therefore do not use $exists
    return ScriptLink(UrlEncode($resolved), $link, $class, undef, $title);
  } else {
    $link = GetEditLink($id, "$id?");
    $link .= ($free ? '|' : ' ') . $text if $text and FreeToNormal($text) ne $id;
    $link = "[[$link]]" if $free;
    $link = "[$link]" if $bracket or not $free and $text;
    return $link;
  }
}
```

**Comment by felixp7** [comment]
Thanks for the code sample, I'll try it out at some point. In the mean time, I just got used to the existing behavior.
