### ISSUE TITLE
Comment signing quirk

### ISSUE THREAD

**Issue by felixp7** [kensanata/oddmuse#9]
This is an odd one. I wasn't able to find an error message in the logs, and worse, the behavior differs between my dev and production server. But for what it's worth...

When trying to submit a comment, if the username I fill in ends in an exclamation mark (a.k.a. bang), OddMuse either seems to crash (?!) and never registers the comment, or -- on another server -- ignores the given username and records the comment as anonymous. There seem to be no lasting side effects in either case.

That pesky punctuation is not important, of course, but it did give me a fright at first.

**Comment by AlexDaniel** [comment]
Oh wow, I just tried it on oddmuse.org and indeed it left a comment as anonymous. That's a wonderful find.

**Comment by kensanata** [comment]
Interesting! Probably because it's an illegal page name. We really ought to allow exclamation marks.

**Comment by kensanata** [comment]
Implemented in 51b2430. Let me know if it works.

**Comment by felixp7** [comment]
That's odd... in my local test environment, this new version doesn't even show the comment form. Admittedly said environment is a bit weird, but 2.3.8 works there.

**Comment by kensanata** [comment]
You probably need to set [$CommentsPrefix](https://oddmuse.org/wiki/CommentsPrefix).

**Comment by felixp7** [comment]
It's set. I used the existing setup, and just dropped the new wiki.pl in. Then dropped the old one back to make sure.

**Comment by kensanata** [comment]
I am at a loss. When I tried it, I had a link to Comments_on_HomePage from HomePage.

**Comment by kensanata** [comment]
How are we going to proceed now? It would seem to me that we can close this issue except for the missing "user acceptance test". :)

**Comment by felixp7** [comment]
Oh, the link is there, the comment page is there, but the comment *form* doesn't show up.

I'd say set this fix aside for now, as it wasn't all that important. Maybe you can try again some other time.

**Comment by kensanata** [comment]
Actually, I think I found a problem related to issue #12. Hopefully da06278 fixes this, and that should restore the comment form, too. The give-away was that the comment page is there but it has no title: the name of the comment page is actually undefined. The commit I mentioned should fix that.

**Comment by felixp7** [comment]
The comment form now shows up and seems to work fine. But now I see the "Homepage URL" field doesn't seem to undergo any validation. Simply changing the input type to "url" would at least prevent honest mistakes.

**Comment by kensanata** [comment]
I'm not sure we can do this since Oddmuse still emits XHTML 1.0. Somebody would have to try and report back?

**Comment by felixp7** [comment]
Eh, just one more detail to take care of when you change the output to html5. Thanks for everything!
